pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  # Not required for lighthouse

lighthouse:
  am_lighthouse: true
  interval: 60
  hosts:
    # Should be empty on lighthouse configuration

listen:
  # To listen on both any ipv4 and ipv6 use "[::]"
  host: 0.0.0.0
  port: 4242
  
punchy:
  punch: true

# uncomment for chachapoly cipher. Options are chachapoly or aes (default)
# NOTE: all nodes in a Nebula network MUST use same cipher
#cipher: chachapoly

tun:
  # lighthouse do not need a tun, hence started without a local tun interface (and therefore without root)
  disabled: true
  
# Configure logging level
logging:
  # panic, fatal, error, warning, info, or debug. Default is info
  level: info
  # json or text formats currently available. Default is text
  format: text

# Nebula security group configuration
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # icmp is allowed during setup, can be removed too
    - port: any
      proto: icmp
      host: any
